## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np     #importing Numpy

A=([[ 5, 10, 15],         #defining two matrixes
    [20, 25, 30],
    [35, 40, 45]])

B=([[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

z=np.array(A)        #turning every matrix into an array to use numby methods on them

x=np.array(B)

In [13]:
mult=z*x           #multiply two matrixes

mult

array([[  5,  20,  45],
       [ 80, 125, 180],
       [245, 320, 405]])

## Write a NumPy program to compute the determinant of a given square array

In [14]:
z**2                #squaring the matrix

array([[  25,  100,  225],
       [ 400,  625,  900],
       [1225, 1600, 2025]], dtype=int32)

## Write a NumPy program to compute the cross product of two given vectors

In [3]:
v=np.array([1,2,3])   #defining two matrixes as an array to use numby methods on them

d=np.array([4,5,6])

result_cross= np.cross(v,d)      #using cross method to calculate cross peoduct of two matrixes

result_cross

array([-3,  6, -3])

## Write a NumPy program to compute the condition number of a given matrix

In [5]:
A=np.array([[ 5, 10, 15],                 # defining a matrix as an array to use numby methods on it
            [20, 25, 30],
            [35, 40, 45]])

condition_numb= np.linalg.cond(A)    #using linalg from numby and using its method called cond to calculate condition number

In [6]:
condition_numb

3.555784549238136e+16

## Write a NumPy program to compute the inverse of a given matrix

In [14]:
k=np.array([[1,2,3],[6,4,5],[6,7,8]])      # defining a matrix as an array to use numby methods on it

result_inv= np.linalg.inv(k)     #using linalg from numby and using its method called inv to calculate inverse of matrix

result_inv

array([[-0.2       ,  0.33333333, -0.13333333],
       [-1.2       , -0.66666667,  0.86666667],
       [ 1.2       ,  0.33333333, -0.53333333]])